cascade:
  model_type: Global_EXC_2Hz_smoothing300ms
data:
  apply_baseline_subtraction: true
  baseline_percentile: 8
  calcium_dataset: CellResp
  input_dir: raw_trace_data_2018
  is_raw: false
  output_dir: processed_spike_voxels_2018
  skip_subjects: []
  test_run_neurons: null
  window_length: 30.0
processing:
  batch_size: 10000
  num_neurons_viz: 10
  original_sampling_rate: 2.1
  seed: 42
  target_sampling_rate: 2.0
  workers: 1
volumization:
  dtype: float16
  volume_shape: [256, 128, 30]
